## FIRST LINE/ROW: Info & Status

# easily enable/disable by uncommenting disabled = true/false

# You can see the symbols after nerd fonts has been installed. sorry.
# First param â”€â”Œ
[username]
format = " [â•­â”€](bright-white)[$user]($style)[ğŸ’€](bright-white)"
style_user = "bold dimmed white"
style_root = "bold red"
show_always = true
#disabled = false

# Second param
[hostname]
format = "[$hostname]($style) "
style = "bold dimmed white"
trim_at = "-"
ssh_only = false
disabled = false

# Third param
[directory]
style = "bright-cyan"
truncation_length = 2
truncate_to_repo = true
truncation_symbol = ""
home_symbol = "~"
read_only = "ğŸ”’"
read_only_style = "red"
fish_style_pwd_dir_length = 1
disabled = false

# Before all the version info (python, nodejs, php, etc.)
[git_status]
style = "purple"
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
deleted = "[ğŸ—‘](dimmed white)"
conflicted = "[ğŸ³](bold red)"
up_to_date = "[âœ“](bold bright-green)"
untracked = "[_(bold white)[?](bright-yellow)_](bold white)"
stashed = "[ğŸ“¦](dimmed yellow)"
modified = "[ğŸ“](fg:red bg:white)"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
disabled = false

# Last param in the first line/row
[time]
format = " [ï‰“ ](white) [$time]($style)\n"
time_format = "%D %I:%M%P"
style = "bright-cyan"
disabled = false

# Prompt: param 2 â””â”€
[character]
success_symbol = " [â•°â”€](bright-white)[îˆ± ](bold white)"
error_symbol = " [Ã—](bold red)"
disabled = false

# SYMBOLS
[status]
symbol = "ï€† "
format = '[\[$symbol$status_common_meaning$status_signal_name$status_maybe_int\]]($style)'
map_symbol = true
disabled = false

[cmd_duration]
min_time = 1000
format = "took [$duration](bold yellow)"
disabled = false

[aws]
style = "bright-white"
symbol = "S3:îŒ½ "
#disabled = true

[gcloud]
symbol = îŒ½ 
#disabled = true

[conda]
symbol = "ï„Œ "
#disabled = false

[dart]
symbol = "î˜ "
#disabled = false

[docker_context]
style = "bright-blue"
symbol = "ïŒˆ "
#disabled = false

[elixir]
symbol = "î˜­ "
#disabled = false

[elm]
symbol = "î˜¬ "
#disabled = false

[git_branch]
style = "bright-blue"
symbol = "ï„“ "
#disabled = false

[golang]
symbol = "î˜§ "
#disabled = false

#[haskell]
#symbol = "î˜Ÿ "
#disabled = false

[hg_branch]
symbol = "ï¬« "
#disabled = false

[java]
symbol = "î‰– "
#disabled = false

[julia]
symbol = "î˜¤ "
#disabled = false

[nim]
symbol = "ïš¤ "
#disabled = false

[nix_shell]
symbol = "ïŒ“ "
#disabled = false

[nodejs]
symbol = "îœ˜ "
#disabled = false

[package]
symbol = "ï£– "
#disabled = false

[perl]
symbol = "î© "
#disabled = false

[php]
symbol = "ï  "
#disabled = false

[python]
style = "bright-green"
symbol = "î˜† "
#disabled = false

[ruby]
style = "bright-red"
symbol = "îˆ¾ "
#disabled = false

[rust]
symbol = "î¨ "
#disabled = false

[swift]
symbol = "ï¯£ "
#disabled = false

[memory_usage]
disabled = false
threshold = -1
#format = "$symbol [${ram}( ${ram_pct})]($style) " example: 2.2/32G 7% (used)
format = "$symbol [${ram_pct}]($style) "
symbol = "[ğŸ](bright-white)"
style = "bold bright-red"
disabled = false
