## FIRST LINE/ROW: Info & Status

# You can see the symbols after nerd fonts has been installed. sorry.
# First param â”€â”Œ
[username]
format = " [â•­â”€](bright-white)[$user]($style)[@](green)"
style_user = "bold dimmed white"
style_root = "bold red"
show_always = true

# Second param
[hostname]
format = "[$hostname]($style) [in](white) "
style = "bold dimmed white"
trim_at = "-"
ssh_only = false
disabled = false

# Third param
[directory]
style = "purple"
truncation_length = 0
truncate_to_repo = true
truncation_symbol = "repo: "

# Before all the version info (python, nodejs, php, etc.)
[git_status]
style = "green"
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
deleted = "x"


# Last param in the first line/row
[time]
format = " [ï‰“ ](white) [$time]($style)\n"
time_format = "%D %I:%M%P"
style = "bright-cyan"
disabled = false

# Prompt: param 2 â””â”€
[character]
success_symbol = " [â•°â”€](bright-white)[îˆ± ](bold white)"
error_symbol = " [Ã—](bold red)"
#use_symbol_for_status = true

# SYMBOLS
[status]
symbol = "ï€† "
# "ğŸ”´"
format = '[\[$symbol$status_common_meaning$status_signal_name$status_maybe_int\]]($style)'
map_symbol = true
disabled = false

[aws]
style = "bright-white"
symbol = "S3:îŒ½ "

[conda]
symbol = "ï„Œ "

[dart]
symbol = "î˜ "

[docker_context]
style = "bright-blue"
symbol = "ïŒˆ "
disabled = true

[elixir]
symbol = "î˜­ "
# "î‰µ "

[elm]
symbol = "î˜¬ "

[git_branch]
style = "bright-cyan"
symbol = "ï„“ "
# "ï˜ "

[golang]
symbol = "î˜§ "

#[haskell]
#symbol = "î˜Ÿ "

[hg_branch]
symbol = "ï¬« "
#"ï˜ "

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ïŒ“ "
#symbol = "ï‹œ "

[nodejs]
symbol = "îœ˜ "
#symbol = "î‰ "

[package]
symbol = "ï£– "

[perl]
symbol = "î© "

[php]
symbol = "ï  "
#symbol = "î˜ˆ "

[python]
style = "bright-green"
symbol = "î˜† "

[ruby]
style = "bright-red"
symbol = "îˆ¾ "

[rust]
symbol = "î¨ "

[swift]
symbol = "ï¯£ "
