## FIRST LINE/ROW: Info & Status

# You can see the symbols after nerd fonts has been installed. sorry.
# First param â”€â”Œ
[username]
format = " [â•­â”€](dimmed red)[$user]($style)[ğŸ’€](bright-white)"
style_user = "bright-white"
style_root = "red"
show_always = true

# Second param
[hostname]
format = "[$hostname]($style) "
style = "bright-white"
trim_at = "-"
ssh_only = false
disabled = false

# Third param
[directory]
style = "bright-cyan"
truncation_length = 2
truncate_to_repo = true
truncation_symbol = ""
home_symbol = "~"
read_only = "ğŸ”’"
read_only_style = "red"

# Before all the version info (python, nodejs, php, etc.)
[git_status]
style = "dimmed purple"
ahead = " â‡¡${count}"
diverged = " â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = " â‡£${count}"
deleted = " ğŸ—‘ (dimmed white)"
conflicted = " ğŸ³  (red)"
up_to_date = "âœ“(bright-blue)"
untracked = "_(white)?(bright-yellow)_(white)"
stashed = " ğŸ“¦ (dimmed yellow)"
modified = " ğŸ“ (dimmed yellow)"
staged = " ++ ($count)](bright-yellow)"
renamed = " ğŸ‘… "

# Last param in the first line/row
[time]
format = " ï‰“ (bright-white) [$time]($style)\n"
time_format = "%D %I:%M%P"
style = "bright-cyan"
disabled = false

# Prompt: param 2 â””â”€
[character]
success_symbol = " [â•°â”€](dimmed red)[îˆ± ](bright-white)"
error_symbol = " î€‰ (bold red)"

# SYMBOLS
[status]
symbol = " ï€† (bright-yellow) "
format = '[$symbol$status_common_meaning$status_signal_name$status_maybe_int]($style)'
sigint_symbol = " KILLED (red)"
map_symbol = true
disabled = false

[cmd_duration]
min_time = 3500
format = 'took [$duration](bold red)'
style = 'red bold'
show_milliseconds = false
disabled = false
show_notifications = false
min_time_to_notify = 65000

[shell]
format = '$indicator '
bash_indicator = 'bsh'
fish_indicator = 'fsh'
zsh_indicator = 'zsh'
powershell_indicator = 'psh'
ion_indicator = 'ion'
elvish_indicator = 'esh'
tcsh_indicator = 'tsh'
nu_indicator = 'nu'
xonsh_indicator = 'xsh'
unknown_indicator = ''
disabled = true

[shlvl]
threshold = 2
format = '[$symbol$shlvl]($style) '
symbol = 'â†•ï¸  '
repeat = false
style = 'bold white'
disabled = true

[aws]
style = "bright-white"
symbol = "S3:îŒ½ "
disabled = true

[gcloud]
symbol = "GC:îŒ½ "
disabled = true

[conda]
style = "bright-green"
symbol = "ï„Œ "

[dart]
symbol = "î˜ "

[docker_context]
style = "bright-blue"
symbol = "ïŒˆ "
disabled = false

[elixir]
symbol = "î˜­ "

[elm]
symbol = "î˜¬ "

[git_branch]
style = "bright-blue"
symbol = "ï„“ "

[golang]
style = "dimmed blue"
symbol = "î˜§ "

[hg_branch]
symbol = "ï¬« "

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ïŒ“ "

[nodejs]
symbol = "îœ˜ "
disabled = true

[package]
symbol = "ï£– "

[perl]
symbol = "î© "

[php]
symbol = "ï  "

[python]
style = "bright-green"
symbol = "î˜† "

[ruby]
style = "bright-red"
symbol = "îˆ¾ "

[rust]
symbol = "î¨ "

[swift]
symbol = "ï¯£ "

[memory_usage]
threshold = -1
format = "$symbol [${ram_pct}]($style) "
symbol = "[ğŸ](bright-white)"
style = "bold bright-red"
disabled = false
